# Generated by Django 5.0.3 on 2024-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='producto_images/'),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='tipo_producto_images/'),
        ),
    ]
