# Generated by Django 5.0.3 on 2024-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_tipoproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='tipo_productos_images/'),
        ),
    ]
