# Generated by Django 5.0.3 on 2024-03-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_alter_tipoproducto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtipo', models.CharField(choices=[('Salida', 'Salida'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('rcantidad', models.IntegerField()),
                ('rrazon', models.CharField(choices=[('Expiró', 'Expiró'), ('Compra', 'Compra'), ('Traslado', 'Traslado')], max_length=20)),
                ('rfecha', models.DateTimeField(auto_now_add=True)),
                ('rproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('rusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
