# Generated by Django 5.0.3 on 2024-03-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_ventageneral_productoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproducto',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Expiró', 'Expiró'), ('Traslado', 'Traslado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroproducto',
            name='rtipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ventageneral',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
