# Generated by Django 5.0.3 on 2024-03-29 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_registroproducto_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproducto',
            name='rrazon',
            field=models.CharField(choices=[('Traslado', 'Traslado'), ('Compra', 'Compra'), ('Expiró', 'Expiró')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroproducto',
            name='rtipo',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ventageneral',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 29, 21, 14, 1, 619598, tzinfo=datetime.timezone.utc)),
        ),
    ]
