# Generated by Django 5.0.3 on 2024-03-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_registroproducto_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproducto',
            name='rrazon',
            field=models.CharField(choices=[('Expiró', 'Expiró'), ('Compra', 'Compra'), ('Traslado', 'Traslado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventageneral',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventageneral',
            name='tipo_comprobante',
            field=models.CharField(choices=[('Boleta Electronica', 'Boleta Electronica'), ('Factura Electronica', 'Factura Electronica')], max_length=100),
        ),
    ]
